#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/dani77/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
dunst &
cbatticon &
volumeicon &
nm-applet &
redshift-gtk -l 41.6:-8.62 &
udiskie -at &
conky -c .conkyrc &
conky -c .conkyrc1 &
fbsetbg -f Wallpaper/macos-monterey-wwdc-21-stock-dark-mode-5k-3840x2160-5585.jpg &
xrdb merge ~/.Xresources &
#setxkbmap de deadtilde &
/usr/bin/octoxbps-notifier &
xautolock -time 5 -locker slock &
xterm -e vi README &
exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/dani77/.fluxbox/log"
