# Application Launchers
bind=SUPER,space,spawn,noctalia msg panel-toggle launcher
bind=SUPER,comma,spawn,noctalia msg settings-toggle
bind=SUPER,l,spawn,noctalia msg session lock
bind=SUPER,n,spawn,noctalia msg panel-toggle clipboard
bind=SUPER,x,spawn,noctalia msg panel-toggle session
bind=SUPER,y,spawn,noctalia msg panel-toggle wallpaper

# Terminal
bind=SUPER,t,spawn,kitty

# Exit
bind=ALT,m,quit
bind=SUPER,q,killclient,

# Security
bind=SUPER+ALT,l,spawn,noctalia ipc lockScreen lock

# Audio Controls
bind=NONE,XF86AudioRaiseVolume,spawn,noctalia ipc volume increase 3
bind=NONE,XF86AudioLowerVolume,spawn,noctalia ipc volumedecrease 3
bind=NONE,XF86AudioMute,spawn,noctalia ipc volume muteOutput

# Brightness Controls
bind=NONE,XF86MonBrightnessUp,spawn,noctalia ipc brightness increase 5
bind=NONE,XF86MonBrightnessDown,spawn,noctalia ipc brightness decrease 5
